import React from "react";
import { Navbar } from "@/features/home/components/navbar";

type Props = {};

export function MainLayout({}: Props) {
  return (
    <div className="homepage w-full">
      <Navbar />
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
      <h1>"test"</h1>
    </div>
  );
}
